version: '3.8'
services:
  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 將 React 的 Nginx 暴露到本地主機的 3000 埠
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Go 後端服務
networks:
  app-network:
    driver: bridge
